-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1 sec <<< FAILURE!
websocketSinkAndSourceTestCase(org.wso2.extension.siddhi.io.websocket.sink.WebsocketSinkTestCase)  Time elapsed: 0.508 sec  <<< FAILURE!
java.lang.NullPointerException
	at org.wso2.extension.siddhi.io.websocket.sink.WebsocketSink.connect(WebsocketSink.java:118)
	at org.wso2.siddhi.core.stream.output.sink.Sink.connectWithRetry(Sink.java:163)
	at org.wso2.siddhi.core.SiddhiAppRuntime.start(SiddhiAppRuntime.java:273)
	at org.wso2.extension.siddhi.io.websocket.sink.WebsocketSinkTestCase.websocketSinkAndSourceTestCase(WebsocketSinkTestCase.java:68)

